services:
  postgres:
    container_name: apiNest
    image: postgres:16-alpine
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dalio  
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata:
